include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: nice_nano_v2
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
